In [1]:
import pandas
import pandas as pd
import numpy as np
import sys
import sklearn
from sklearn.metrics import log_loss, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
from tqdm import tqdm

deepctr_path = '/root/linghui/rec-fairness/'
sys.path.append(deepctr_path)
import deepctr
from deepctr.models import *
from deepctr.feature_column import SparseFeat, VarLenSparseFeat, get_feature_names
# from utilis import get_feat_dict

def get_feat_dict(data):
    if data == 'ml-1m':
        feat_dict = {'movie_id': 3706,
                 'user_id': 6040,
                 'gender': 2,
                 'age': 7,
                 'occupation': 21,
                 'zipcode': 3439}
    if data == 'black-fri':
        feat_dict = {'user_id': 5891,
                 'product_id': 3631,
                 'gender': 2,
                 'age': 7,
                 'occupation': 21,
                 'city': 3,
                 'stay_years': 5,
                 'martial_status': 2,
                 'cate_1': 20,
                 'cate_2': 18,
                 'cate_3': 16,
                 'price': 23962}
    return feat_dict

2022-07-12 16:46:11.990038: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:
DeepCTR version 0.9.1 detected. Your version is 0.9.0.
Use `pip install -U deepctr` to upgrade.Changelog: https://github.com/shenweichen/DeepCTR/releases/tag/v0.9.1

In [2]:
#load data , black-friday

saved_data_path = '/data/linghui/black-friday/processed_data/'
# train_data_path = saved_data_path + 'train_data.csv' 
# test_data_path = saved_data_path + 'test_data.csv'
train_data_path = saved_data_path + 'train_data_liuyi.csv' 
test_data_path = saved_data_path + 'test_data_liuyi.csv'

#load train_data
train_data = pd.read_csv(train_data_path,index_col=0)

/opt/conda/lib/python3.8/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
train_data

,user_id,product_id,gender,age,occupation,city,stay_years,martial_status,cate_1,cate_2,cate_3,price,label
0,0,672,0,0,10,0,2,0,2,0,0,8370,1
467664,0,2098,0,0,10,0,2,0,7,0,0,7953,1
467663,0,570,0,0,10,0,2,0,2,3,9,11051,1
428894,0,722,0,0,10,0,2,0,2,3,9,10572,1
428893,0,249,0,0,10,0,2,0,0,1,6,15416,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
544172,5890,2207,1,2,6,1,2,0,5,0,0,12570,0
544173,5890,2843,1,2,6,1,2,0,7,0,0,7799,0
544174,5890,1722,1,2,6,1,2,0,1,3,6,6974,0
544175,5890,1910,1,2,6,1,2,0,0,5,5,19391,0
544176,5890,3126,1,2,6,1,2,0,4,7,0,6933,0

In [4]:
#get feature_columns and input data

dataset = 'black-fri'
feat_dict = get_feat_dict(dataset)
train_feats = ['user_id','product_id','gender','age','occupation','city','stay_years','martial_status','cate_1','cate_2','cate_3','price']

fixlen_feature_columns = [SparseFeat(feat, feat_dict[feat], embedding_dim=4)
								  for feat in train_feats]

linear_feature_columns = fixlen_feature_columns
dnn_feature_columns = fixlen_feature_columns

feature_names = get_feature_names(linear_feature_columns + dnn_feature_columns)
train_data = sklearn.utils.shuffle(train_data)

train_model_input = {name: train_data[name].values for name in train_feats}
label = train_data['label'].values

In [8]:
def train_bf_ctr_model(model_name,batch_size, epochs,validation_split=0.2):
    if model_name == 'deepfm':
        model = DeepFM(linear_feature_columns, dnn_feature_columns, task='binary')
    if model_name == 'afm':
        model = AFM(linear_feature_columns, dnn_feature_columns, task='binary')
    if model_name == 'wdl':
        model = WDL(linear_feature_columns, dnn_feature_columns, task='binary')
    if model_name == 'nfm':
        model = NFM(linear_feature_columns, dnn_feature_columns, task='binary')
        
    saved_model_path = '/data/linghui/saved_model/' + model_name + '-black-fri/'
    check_path = saved_model_path + model_name + '-black-fri-liuyi.ckpt'
    
    model.compile(optimizer=tf.keras.optimizers.Adam(), loss='binary_crossentropy',
              metrics=['AUC', 'Precision', 'Recall'])
    model.summary()
    
    checkpoint = tf.keras.callbacks.ModelCheckpoint(check_path, save_weights_only=True,
                                                 save_best_only=True,
                                                 monitor='val_loss')
    print('begain training')
    model.fit(train_model_input, label,
						batch_size=batch_size, epochs=epochs, verbose=2,
                        callbacks=[checkpoint],
						validation_split=validation_split)

In [6]:
batch_size = 256
epochs = 20
model_name = 'deepfm'

train_bf_ctr_model(model_name,batch_size,epochs)